import { useEffect, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router'
import { format } from 'date-fns'
import { jsPDF } from 'jspdf'
import { autoTable } from 'jspdf-autotable'
import * as XLSX from 'xlsx'
import { ArrowLeft, FileDown, FileSpreadsheet } from 'lucide-react'
import { EMPTY_RESULT, SHAREHOLDER_TAX_WITHHELD_RATE, TAX_WITHHELD_RATES } from '@/lib/model'
import { useStore } from '@/lib/store'
import { Money } from '@/components/chrome'
import { Button } from '@/components/ui/button'

const fmtDateTime = (iso: string) => format(new Date(iso), "MMM d, yyyy 'at' h:mm a")
const money2 = (n: number) => n.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
const round2 = (n: number) => Math.round(n * 100) / 100

export default function Handoff() {
  const { id } = useParams<{ id: string }>()
  const store = useStore()
  const dist = store.db.distributions.find((d) => d.id === id)
  const user = store.db.users.find((u) => u.id === store.sessionUserId)
  const { refreshDistribution } = store
  // Stable for the whole visit: the header, page title, and download file
  // names must all reference the same generation time.
  const [now] = useState(() => new Date())
  const generatedAt = fmtDateTime(now.toISOString())

  // Fresh snapshot + computation whenever this page is opened directly.
  useEffect(() => {
    if (id) refreshDistribution(id).catch(() => {})
  }, [refreshDistribution, id])

  useEffect(() => {
    if (!dist) return
    document.title = `Name: ${dist.name} · Generated At: ${generatedAt}`
    return () => { document.title = 'Bonus & Dividend Calculator' }
  }, [dist, generatedAt])

  if (!dist) {
    if (store.bootstrapping) {
      return <div className="py-10 text-center text-sm text-muted-foreground">Loading…</div>
    }
    return <Navigate to="/" replace />
  }

  const result = store.computations[dist.id]
  const fileStamp = `${dist.name.replace(/\s+/g, '_')}_${format(now, 'yyyyMMdd_HHmm')}`

  // Repeated at the top of every printed page via print-only table header rows.
  const printHeader = (
    <div className="mb-2 flex flex-wrap items-end justify-between gap-x-6 gap-y-1 border-b pb-2">
      <div>
        <div className="font-display text-lg font-semibold tracking-tight">Name: {dist.name}</div>
        <div className="text-xs text-muted-foreground">
          Generated At: <span className="font-medium text-foreground">{generatedAt}</span>
        </div>
      </div>
      <div className="text-xs text-muted-foreground">
        Generated by <span className="font-medium text-foreground">{user?.username}</span>
      </div>
    </div>
  )

  // Hardcoded withholding: bonuses follow the employee classification,
  // dividends the shareholder rate. Classification comes from the
  // snapshot's employee (personId is the employee id for merged persons).
  const rows = (result?.payouts ?? []).map((p) => {
    const bonuses = p.bonusEffort + p.bonusImpact + p.specialBonus
    const classification = store.db.employees.find((e) => e.id === p.personId)?.classification ?? null
    const bonusTax = bonuses * (classification ? TAX_WITHHELD_RATES[classification] : 0)
    const dividendTax = p.dividends * SHAREHOLDER_TAX_WITHHELD_RATE
    return { p, bonuses, bonusTax, dividendTax, net: p.total - bonusTax - dividendTax }
  })

  const totals = rows.reduce(
    (s, r) => ({
      bonuses: s.bonuses + r.bonuses,
      bonusTax: s.bonusTax + r.bonusTax,
      dividends: s.dividends + r.p.dividends,
      dividendTax: s.dividendTax + r.dividendTax,
      total: s.total + r.p.total,
      net: s.net + r.net,
    }),
    { bonuses: 0, bonusTax: 0, dividends: 0, dividendTax: 0, total: 0, net: 0 },
  )
  const r = result ?? EMPTY_RESULT
  const dividends = r.dividends
  const sharesTotal = dividends.reduce((s, d) => s + d.shares, 0)
  const dividendTotal = dividends.reduce((s, d) => s + d.amount, 0)

  const downloadPdf = () => {
    const doc = new jsPDF({ orientation: 'landscape' })
    const pageWidth = doc.internal.pageSize.getWidth()
    const headerLine = `Generated by ${user?.username}  ·  Generated At: ${generatedAt}`

    const drawHeader = () => {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(14)
      doc.setTextColor(28, 25, 23)
      doc.text(`Name: ${dist.name}`, 14, 15)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(120, 113, 108)
      doc.text(headerLine, 14, 21)
    }

    let lastY = 28
    const trackY = (data: { cursor?: { y: number } | null }) => {
      if (data.cursor) lastY = data.cursor.y
    }
    const tableBase = {
      margin: { left: 14, right: 14, top: 26 },
      theme: 'grid' as const,
      styles: { halign: 'right' as const, cellPadding: 2 },
      columnStyles: { 0: { halign: 'left' as const, fontStyle: 'bold' as const } },
      headStyles: { fillColor: [41, 37, 36] as [number, number, number], textColor: 255 },
      footStyles: { fillColor: [231, 229, 228] as [number, number, number], textColor: 28, fontStyle: 'bold' as const },
      didDrawPage: (data: { cursor?: { y: number } | null }) => {
        trackY(data)
        drawHeader()
      },
    }

    autoTable(doc, {
      ...tableBase,
      head: [['Name', 'Bonuses', 'Tax on Bonuses', 'Dividends', 'Tax on Dividends', 'Total', 'Total Less Taxes']],
      body: rows.map(({ p, bonuses, bonusTax, dividendTax, net }) => [
        p.name, money2(bonuses), money2(bonusTax), money2(p.dividends), money2(dividendTax), money2(p.total), money2(net),
      ]),
      foot: [['Total', money2(totals.bonuses), money2(totals.bonusTax), money2(totals.dividends), money2(totals.dividendTax), money2(totals.total), money2(totals.net)]],
    })

    if (dividends.length > 0) {
      autoTable(doc, {
        ...tableBase,
        startY: lastY + 10,
        head: [['Name', 'Shares', 'Dividend']],
        body: dividends.map((d) => [d.name, d.shares.toLocaleString(), money2(d.amount)]),
        foot: [['Total', sharesTotal.toLocaleString(), money2(dividendTotal)]],
      })
    }

    const pages = doc.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(120, 113, 108)
      doc.text(`Page ${i} of ${pages}`, pageWidth - 14, doc.internal.pageSize.getHeight() - 7, { align: 'right' })
    }

    doc.save(`${fileStamp}.pdf`)
  }

  const downloadExcel = () => {
    const wb = XLSX.utils.book_new()

    const personSheet = XLSX.utils.aoa_to_sheet([
      ['Name', 'Bonuses', 'Tax on Bonuses', 'Dividends', 'Tax on Dividends', 'Total', 'Total Less Taxes'],
      ...rows.map(({ p, bonuses, bonusTax, dividendTax, net }) => [
        p.name, round2(bonuses), round2(bonusTax), round2(p.dividends), round2(dividendTax), round2(p.total), round2(net),
      ]),
      ['Total', round2(totals.bonuses), round2(totals.bonusTax), round2(totals.dividends), round2(totals.dividendTax), round2(totals.total), round2(totals.net)],
    ])
    personSheet['!cols'] = [{ wch: 30 }, ...Array.from({ length: 6 }, () => ({ wch: 16 }))]
    XLSX.utils.book_append_sheet(wb, personSheet, 'Per-person totals')

    if (dividends.length > 0) {
      const shSheet = XLSX.utils.aoa_to_sheet([
        ['Name', 'Shares', 'Dividend'],
        ...dividends.map((d) => [d.name, d.shares, round2(d.amount)]),
        ['Total', sharesTotal, round2(dividendTotal)],
      ])
      shSheet['!cols'] = [{ wch: 30 }, { wch: 12 }, { wch: 16 }]
      XLSX.utils.book_append_sheet(wb, shSheet, 'Shareholders')
    }

    XLSX.writeFile(wb, `${fileStamp}.xlsx`)
  }

  return (
    <div className="space-y-8 px-6 py-10 print:px-0 print:py-4">
      <div>
        <div className="mb-3 flex items-center justify-end gap-2 print:hidden">
          <Button variant="outline" size="sm" onClick={downloadPdf} disabled={!result}>
            <FileDown className="mr-1.5 h-4 w-4" /> PDF
          </Button>
          <Button variant="outline" size="sm" onClick={downloadExcel} disabled={!result}>
            <FileSpreadsheet className="mr-1.5 h-4 w-4" /> Excel
          </Button>
        </div>
        <Link to={`/distributions/${dist.id}`} className="mb-3 inline-flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground print:hidden">
          <ArrowLeft className="h-3.5 w-3.5" /> Back to distribution
        </Link>
        <div className="flex flex-wrap items-end justify-between gap-x-6 gap-y-1 border-b pb-3">
          <div>
            <h1 className="font-display text-2xl font-semibold tracking-tight">Name: {dist.name}</h1>
            <p className="mt-0.5 text-xs text-muted-foreground">
              Generated At: <span className="font-medium text-foreground">{generatedAt}</span>
            </p>
          </div>
          <p className="text-xs text-muted-foreground">
            Generated by <span className="font-medium text-foreground">{user?.username}</span>
          </p>
        </div>
      </div>

      {!result ? (
        <div className="py-10 text-center text-sm text-muted-foreground">Loading the computation…</div>
      ) : (
        <>
          <section>
            <h2 className="kicker mb-2">Per-person totals</h2>
            <div className="overflow-x-auto rounded-lg border">
              <table className="ledger min-w-[52rem] print:min-w-0">
                <thead>
                  <tr className="hidden print:table-row">
                    <th colSpan={7} className="!p-0 text-left normal-case tracking-normal">{printHeader}</th>
                  </tr>
                  <tr>
                    <th>Name</th>
                    <th className="r">Bonuses</th>
                    <th className="r">Tax on Bonuses</th>
                    <th className="r">Dividends</th>
                    <th className="r">Tax on Dividends</th>
                    <th className="r">Total</th>
                    <th className="r">Total Less Taxes</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map(({ p, bonuses, bonusTax, dividendTax, net }) => (
                    <tr key={p.personId ?? p.name}>
                      <td className="font-medium">{p.name}</td>
                      <td className="r"><Money value={bonuses} /></td>
                      <td className="r"><Money value={bonusTax} /></td>
                      <td className="r"><Money value={p.dividends} /></td>
                      <td className="r"><Money value={dividendTax} /></td>
                      <td className="r"><Money value={p.total} className="font-semibold" /></td>
                      <td className="r"><Money value={net} className="font-semibold" /></td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr>
                    <td className="font-semibold">Total</td>
                    <td className="r"><Money value={totals.bonuses} className="font-semibold" /></td>
                    <td className="r"><Money value={totals.bonusTax} className="font-semibold" /></td>
                    <td className="r"><Money value={totals.dividends} className="font-semibold" /></td>
                    <td className="r"><Money value={totals.dividendTax} className="font-semibold" /></td>
                    <td className="r"><Money value={totals.total} className="font-semibold" /></td>
                    <td className="r"><Money value={totals.net} className="font-semibold" /></td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </section>

          <section>
            <h2 className="kicker mb-2">Shareholders</h2>
            <div className="overflow-x-auto rounded-lg border">
              <table className="ledger min-w-[36rem] print:min-w-0">
                <thead>
                  <tr className="hidden print:table-row">
                    <th colSpan={3} className="!p-0 text-left normal-case tracking-normal">{printHeader}</th>
                  </tr>
                  <tr><th>Name</th><th className="r">Shares</th><th className="r">Dividend</th></tr>
                </thead>
                <tbody>
                  {r.dividends.map((d) => (
                    <tr key={d.shareholderId}>
                      <td className="font-medium">{d.name}</td>
                      <td className="r num">{d.shares.toLocaleString()}</td>
                      <td className="r"><Money value={d.amount} className="font-semibold" /></td>
                    </tr>
                  ))}
                  {r.dividends.length === 0 && (
                    <tr><td colSpan={3} className="py-6 text-center text-sm text-muted-foreground">No shareholders in this distribution.</td></tr>
                  )}
                </tbody>
                {r.dividends.length > 0 && (
                  <tfoot>
                    <tr>
                      <td className="font-semibold">Total</td>
                      <td className="r num font-semibold">
                        {r.dividends.reduce((s, d) => s + d.shares, 0).toLocaleString()}
                      </td>
                      <td className="r">
                        <Money value={r.dividends.reduce((s, d) => s + d.amount, 0)} className="font-semibold" />
                      </td>
                    </tr>
                  </tfoot>
                )}
              </table>
            </div>
          </section>
        </>
      )}
    </div>
  )
}
