import { useEffect } from 'react'
import { Link, Navigate, useParams } from 'react-router'
import { format } from 'date-fns'
import { ArrowLeft } from 'lucide-react'
import { EMPTY_RESULT } from '@/lib/model'
import { useStore } from '@/lib/store'
import { Money } from '@/components/chrome'

const fmtDateTime = (iso: string) => format(new Date(iso), "MMM d, yyyy 'at' h:mm a")

export default function Handoff() {
  const { id } = useParams<{ id: string }>()
  const store = useStore()
  const dist = store.db.distributions.find((d) => d.id === id)
  const user = store.db.users.find((u) => u.id === store.sessionUserId)
  const { refreshDistribution } = store

  // Fresh snapshot + computation whenever this page is opened directly.
  useEffect(() => {
    if (id) refreshDistribution(id).catch(() => {})
  }, [refreshDistribution, id])

  if (!dist) {
    if (store.bootstrapping) {
      return <div className="py-10 text-center text-sm text-muted-foreground">Loading…</div>
    }
    return <Navigate to="/" replace />
  }

  const result = store.computations[dist.id]

  const totals = (result?.payouts ?? []).reduce(
    (s, p) => ({
      bonuses: s.bonuses + p.bonusEffort + p.bonusImpact + p.specialBonus,
      dividends: s.dividends + p.dividends,
      total: s.total + p.total,
    }),
    { bonuses: 0, dividends: 0, total: 0 },
  )
  const r = result ?? EMPTY_RESULT

  return (
    <div className="mx-auto max-w-3xl space-y-8 px-4 py-10">
      <div>
        <Link to={`/distributions/${dist.id}`} className="mb-3 inline-flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground">
          <ArrowLeft className="h-3.5 w-3.5" /> Back to distribution
        </Link>
        <h1 className="font-display text-2xl font-semibold tracking-tight">{dist.name}</h1>
        <div className="mt-2 flex flex-wrap gap-2 text-xs">
          <span className="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-medium text-muted-foreground">
            Generated by <span className="text-foreground">{user?.username}</span>
          </span>
          <span className="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-medium text-muted-foreground">
            Generated at <span className="text-foreground">{fmtDateTime(new Date().toISOString())}</span>
          </span>
        </div>
      </div>

      {!result ? (
        <div className="py-10 text-center text-sm text-muted-foreground">Loading the computation…</div>
      ) : (
        <>
          <section>
            <h2 className="kicker mb-2">Per-person totals</h2>
            <div className="overflow-x-auto rounded-lg border">
              <table className="ledger">
                <thead>
                  <tr><th>Name</th><th className="r">Bonuses</th><th className="r">Dividends</th><th className="r">Total</th></tr>
                </thead>
                <tbody>
                  {r.payouts.map((p) => {
                    const bonuses = p.bonusEffort + p.bonusImpact + p.specialBonus
                    return (
                      <tr key={p.personId ?? p.name}>
                        <td className="font-medium">{p.name}</td>
                        <td className="r"><Money value={bonuses} /></td>
                        <td className="r"><Money value={p.dividends} /></td>
                        <td className="r"><Money value={p.total} className="font-semibold" /></td>
                      </tr>
                    )
                  })}
                </tbody>
                <tfoot>
                  <tr>
                    <td className="font-semibold">Total</td>
                    <td className="r"><Money value={totals.bonuses} className="font-semibold" /></td>
                    <td className="r"><Money value={totals.dividends} className="font-semibold" /></td>
                    <td className="r"><Money value={totals.total} className="font-semibold" /></td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </section>

          <section>
            <h2 className="kicker mb-2">Shareholders</h2>
            <div className="overflow-x-auto rounded-lg border">
              <table className="ledger">
                <thead>
                  <tr><th>Name</th><th className="r">Shares</th><th className="r">Dividend</th></tr>
                </thead>
                <tbody>
                  {r.dividends.map((d) => (
                    <tr key={d.shareholderId}>
                      <td className="font-medium">{d.name}</td>
                      <td className="r num">{d.shares.toLocaleString()}</td>
                      <td className="r"><Money value={d.amount} className="font-semibold" /></td>
                    </tr>
                  ))}
                  {r.dividends.length === 0 && (
                    <tr><td colSpan={3} className="py-6 text-center text-sm text-muted-foreground">No shareholders in this distribution.</td></tr>
                  )}
                </tbody>
                {r.dividends.length > 0 && (
                  <tfoot>
                    <tr>
                      <td className="font-semibold">Total</td>
                      <td className="r num font-semibold">
                        {r.dividends.reduce((s, d) => s + d.shares, 0).toLocaleString()}
                      </td>
                      <td className="r">
                        <Money value={r.dividends.reduce((s, d) => s + d.amount, 0)} className="font-semibold" />
                      </td>
                    </tr>
                  </tfoot>
                )}
              </table>
            </div>
          </section>
        </>
      )}
    </div>
  )
}
